### ISSUE TITLE
怎么连接到硬件

### ISSUE THREAD

**Issue by Larry955** [heyangHEY/HeyAR_ChatBot#1]
hello，可否提供个连接到硬件的教程

**Comment by heyangHEY** [comment]
> hello，可否提供个连接到硬件的教程

ubuntu系统接上蓝牙耳机，然后在系统 设置-声音 页面，配置好输出、输入。
用 "./test/4_pyaudio检测麦克风和扬声器.ipynb" 这个notebook，确定一下你的蓝牙耳机叫什么，然后填入 config.yml，大概率用 “pulse” 就行。
```yaml
AUDIO:
    General: 
        input:
            name: pulse
        output:
            name: pulse
```
测试拾音和播放功能。
然后按照readme，安装代码的环境。
到火山引擎注册账号，实名认证，然后开通大模型语音合成双向流式TTS（这个功能还需要企业认证，后期我可能会加上非流式的TTS，响应速度慢些，但无需企业认证。）
从火山引擎中找到 app_id 和 access_token，填入 config.yml
```yaml
TTS:
    DouBaoTTS:
        app_id: [填上你的app id]
        access_token: [填上你的access token]
```
如果服务没正常启动，可以调整日志等级
```yaml
base:
    log:
        level: DEBUG
```
然后查看日志。
